export const menuItems=[
    {
        name:"Home",
        id:"home",
        link:"/home",
    },
    {
        name:"About",
        id:"about",
        link:"/about"
    },
    {
        name:"Experience",
        id:"experience",
        link:"/experience"
    },
    {
        name:"Project",
        id:"project",
        link:"/project"
    },
    {
        name:"Contact",
        id:"contact",
        link:"/contact"
    }
]
export const header=[
    {
        port:"Port",
        folio:"folio"
    }
]